### ISSUE TITLE
Flex布局

### ISSUE THREAD

**Issue by taoistwar** [taoistwar/notes#221]
## 垂直居中 & 水平居中
- HTML
```html
<div class="container">
  <img src="/assets/docs/mvp.drawio.svg" />
</div>
```
- 样式
```css
.container {
  display: flex;
  justify-content: center;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```
